/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PieChart: typeof import('./src/components/PieChart.vue')['default']
    SliderGroup: typeof import('./src/components/SliderGroup.vue')['default']
    SmartSlider: typeof import('./src/components/SmartSlider.vue')['default']
    SurveyModal: typeof import('./src/components/SurveyModal.vue')['default']
    TutorialOverlay: typeof import('./src/components/tutorial/TutorialOverlay.vue')['default']
    TutorialWelcomeModal: typeof import('./src/components/tutorial/TutorialWelcomeModal.vue')['default']
  }
}
